# Generated by Django 4.1.6 on 2023-02-12 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='availabal',
            new_name='available',
        ),
    ]
